[template]
src   = "pg_hba.conf"
dest  = "/etc/postgresql/9.3/main/pg_hba.conf"
uid = 102
gid = 106
mode  = "0640"
keys = [
  "/deis/database",
]
check_cmd = "/app/bin/check {{ .src }}"
reload_cmd = "/usr/local/bin/reload"
